=== volchanskyi/JAXB_XML/test_data/xsd/employees.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
<xs:element name="employees" type="employeesType"/>
<xs:complexType name="employeeType">
<xs:sequence>
<xs:element name="firstname">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="[A-Z]\w*"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="lastname">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="[A-Z]\w*"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="title">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="Engineer"/>
<xs:enumeration value="Manager"/>
<xs:enumeration value="QA"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="hiredate">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="([ADFJMNOS]\w*\s)([0-9]{1,2},)\s([0-9]{4})"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="phone">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="\d{10}"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="email">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value=".+\@.+\..{2,18}"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
</xs:sequence>
<xs:attribute type="xs:string" name="id" use="required"/>
</xs:complexType>
<xs:complexType name="employeesType">
<xs:sequence>
<xs:element type="employeeType" name="employee" maxOccurs="unbounded" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:schema>

=== volchanskyi/JAXB_XML/employees.xml
<?xml version="1.0" encoding="utf-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
	<employee id="385450">
		<firstname>John</firstname>
		<lastname>Muir</lastname>
		<title>Engineer</title>
		<hiredate>October 15, 2005</hiredate>
		<phone>2121234567</phone>
		<email>john_smith@gmail.com</email>
	</employee>
	<employee id="385730">
		<firstname>Christina</firstname>
		<lastname>Aguilera</lastname>
		<title>Manager</title>
		<hiredate>September 1, 2010</hiredate>
		<phone>4157654321</phone>
		<email>christina_johnson_smith@gmail.com</email>
	</employee>
</employees>
